import { Listing } from "./types";

export const sampleListings: Array<Listing> = [
  {
    name: "Google Pixel 6",
    price: 1050,
    daysSincePosted: 20,
    tags: ["Protection", "Well used"],
    likes: 1,
  },
  {
    name: "Google pixel 6 128GB (Kinda Coral)",
    price: 1150,
    daysSincePosted: 13,
    tags: ["Lightly used"],
    likes: 1,
  },
  {
    name: "Pixel 6 Sorta Seafoam",
    price: 1250,
    daysSincePosted: 4,
    tags: ["Lightly used"],
    likes: 11,
  },
  {
    name: "Rhinoshield Pixel 6 Case",
    price: 89,
    daysSincePosted: 30,
    tags: ["Brand new"],
    likes: 2,
  },
  {
    name: "Pixel 6 Pro",
    price: 1200,
    daysSincePosted: 15,
    tags: ["Protection", "Well used"],
    likes: 41,
  },
  {
    name: "Pixel 6 Pro 256Gb",
    price: 1850,
    daysSincePosted: 7,
    tags: ["Protection", "Well used"],
    likes: 5,
  },
  {
    name: "google pixel 6 pro",
    price: 700,
    daysSincePosted: 16,
    tags: ["Protection", "Well used"],
    likes: 41,
  },
  {
    name: "GOOGLE PIXEL 4A 6/128GB BLACK",
    price: 399,
    daysSincePosted: 2,
    tags: ["Lightly used"],
    likes: 16,
  },
  {
    name: "Google Pixel 6 Pro Secondhand",
    price: 1899,
    daysSincePosted: 18,
    tags: ["Like new"],
    likes: 0,
  },
  {
    name: "GOOGLE PIXEL 4A 6/128",
    price: 450,
    daysSincePosted: 2,
    tags: ["Protection", "Like new"],
    likes: 3,
  },
  {
    name: "Google Pixel 6 Pro",
    price: 1650,
    daysSincePosted: 12,
    tags: ["Protection", "Like new"],
    likes: 15,
  },
  {
    name: "Google pixel 6 pro",
    price: 1300,
    daysSincePosted: 30,
    tags: ["Protection", "Like new"],
    likes: 30,
  },
  {
    name: "GOOGLE PIXEL 6 PRO FULL SET FOR SALES !!",
    price: 1899,
    daysSincePosted: 13,
    tags: ["Like new"],
    likes: 3,
  },
  {
    name: "Pixel 6 pro 128gb",
    price: 1750,
    daysSincePosted: 7,
    tags: ["Like new"],
    likes: 1,
  },
  {
    name: "Google Pixel 6 Pro",
    price: 800,
    daysSincePosted: 60,
    tags: ["Protection", "Well used"],
    likes: 54,
  },
  {
    name: "[Used] Pixel 6 256GB",
    price: 1500,
    daysSincePosted: 60,
    tags: ["Like new"],
    likes: 10,
  },
  {
    name: "GOOGLE PIXEL 6 PRO 6GB RAM 128GB ROM ORIGINAL GOOGLE PIXEL",
    price: 1690,
    daysSincePosted: 5,
    tags: ["Well used"],
    likes: 8,
  },
  {
    name: "Google Pixel 6 Pro 128GB screen burn",
    price: 1350,
    daysSincePosted: 120,
    tags: ["Protection", "Well used"],
    likes: 34,
  },
  {
    name: "GOOGLE PIXEL 6 8/256 FOR SALE !",
    price: 1699,
    daysSincePosted: 30,
    tags: ["Lightly used"],
    likes: 5,
  },
  {
    name: "Google Pixel 6 Pro 512GB",
    price: 1999,
    daysSincePosted: 15,
    tags: ["Well used"],
    likes: 10,
  },
  {
    name: "Pixel 6 256GB",
    price: 1350,
    daysSincePosted: 15,
    tags: ["Lightly used"],
    likes: 13,
  },
  {
    name: "GOOGLE PIXEL 6 PRO 128 GB",
    price: 1700,
    daysSincePosted: 23,
    tags: ["Like new"],
    likes: 21,
  },
  {
    name: "Google Pixel 6 Pro White 128G Burn Screen",
    price: 1199,
    daysSincePosted: 90,
    tags: ["Protection", "Well used"],
    likes: 32,
  },
  {
    name: "Google Pixel 5A 6/128",
    price: 750,
    daysSincePosted: 60,
    tags: ["Protection", "Well used"],
    likes: 40,
  },
  {
    name: "Peak Design for Pixel 6 Pro",
    price: 130,
    daysSincePosted: 5,
    tags: ["Like new"],
    likes: 4,
  },
  {
    name: "Pixel 6 Rhinoshield",
    price: 70,
    daysSincePosted: 13,
    tags: ["Like new"],
    likes: 2,
  },
  {
    name: "Google Pixel 6 Pro",
    price: 1500,
    daysSincePosted: 2,
    tags: ["Lightly used"],
    likes: 1,
  },
  {
    name: "Pixel 5A 5G 6/128",
    price: 700,
    daysSincePosted: 60,
    tags: ["Protection", "Like new"],
    likes: 32,
  },
  {
    name: "GOOGLE PIXEL 6 🔥  8GB RAM+128GB ROM 🔥  MYSET 🔥  FULLSET 🔥  CONDITION LIKE NEW 🔥  USED SET 🔥 ",
    price: 1388,
    daysSincePosted: 9,
    tags: ["Used"],
    likes: 3,
  },
  {
    name: "Google Pixel 6",
    price: 1850,
    daysSincePosted: 60,
    tags: ["Like new"],
    likes: 4,
  },
  {
    name: "Pixel 6 8/128 Sorta Seafoam US Set",
    price: 1700,
    daysSincePosted: 150,
    tags: ["Like new"],
    likes: 3,
  },
  {
    name: "Google Pixel 6 Pro 12GB Ram 128GB Rom (Burn In)",
    price: 1199,
    daysSincePosted: 90,
    tags: ["Like new"],
    likes: 45,
  },
  {
    name: "Google Pixel 6 Pro 12GB Ram 128GB Rom (Burn In)",
    price: 1199,
    daysSincePosted: 90,
    tags: ["Like new"],
    likes: 24,
  },
  {
    name: "Google Pixel 6 5G 8GB Ram 128GB Dual Sim - Fullset",
    price: 1389,
    daysSincePosted: 19,
    tags: ["Like new"],
    likes: 8,
  },
  {
    name: "Pixel 6 Pro 512GB",
    price: 2300,
    daysSincePosted: 60,
    tags: ["Protection", "Well used"],
    likes: 11,
  },
  {
    name: "Google Pixel 6 Pro Unlocked Set",
    price: 1850,
    daysSincePosted: 30,
    tags: ["Protection", "Like new"],
    likes: 23,
  },
  {
    name: "Google pixel 6 128gb",
    price: 1280,
    daysSincePosted: 90,
    tags: ["Protection", "Like new"],
    likes: 51,
  },
  {
    name: "Bellroy Leather Case for Pixel 6",
    price: 85,
    daysSincePosted: 2,
    tags: ["Protection", "Like new"],
    likes: 0,
  },
  {
    name: "PIXEL 6 PRO",
    price: 1700,
    daysSincePosted: 90,
    tags: ["Protection", "Like new", "Free delivery"],
    likes: 13,
  },
  {
    name: "Google Pixel 6 Pro Black (Rarely Use)",
    price: 2600,
    daysSincePosted: 240,
    tags: ["Like new"],
    likes: 16,
  },
  {
    name: "GOOGLE PIXEL 6 ( 128GB ) 💥 💥  ACCEPT TRADE IN",
    price: 1399,
    daysSincePosted: 13,
    tags: ["Protection", "Like new", "Free delivery"],
    likes: 5,
  },
  {
    name: "Google Pixel 6 Pro 128GB",
    price: 1600,
    daysSincePosted: 120,
    tags: ["Protection", "Like new"],
    likes: 33,
  },
  {
    name: "USED GOOGLW PIXEL 6 128gb (FREE FULLSET)(FREE GOOGLE DONGLE)(2 months warranty)",
    price: 1364,
    daysSincePosted: 19,
    tags: ["Like new"],
    likes: 7,
  },
  {
    name: "Google Pixel 6 128gb",
    price: 1350,
    daysSincePosted: 8,
    tags: ["Like new"],
    likes: 9,
  },
  {
    name: "Quad Lock for Pixel 6 Pro",
    price: 100,
    daysSincePosted: 60,
    tags: ["Lightly used"],
    likes: 5,
  },
  {
    name: "Google Pixel 6 8GB Ram 128GB/256GB Rom",
    price: 1099,
    daysSincePosted: 180,
    tags: ["Like new"],
    likes: 24,
  },
  {
    name: "Google Pixel 6 8GB Ram 128GB/256GB Rom",
    price: 1099,
    daysSincePosted: 180,
    tags: ["Protection", "Like new"],
    likes: 52,
  },
];
